"""empty message

Revision ID: 02af05c9071a
Revises: 
Create Date: 2020-04-24 12:07:07.062254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02af05c9071a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anteckning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('namnge', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anteckning')
    # ### end Alembic commands ###
